/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 11, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 1.3695218447504247, 4.3467559451296065, 2.2744491294339597 };
const float ei_classifier_anom_mean[3] = { 1.4686471299935826, 3.718970877026871, 2.250466136123036 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { 0.3582003116607666, 0.7993497252464294, 2.164216995239258 }, 0.7140268071379657 },
	{ ( float[3] ) { -0.602409839630127, -0.5277621746063232, -0.3240498900413513 }, 0.3793544723233781 },
	{ ( float[3] ) { -1.0502599477767944, -0.8497599959373474, -0.9757336378097534 }, 0.28292960210181023 },
	{ ( float[3] ) { -0.06443414837121964, -0.46550503373146057, 1.5453177690505981 }, 0.507653175884706 },
	{ ( float[3] ) { 0.10431182384490967, 2.115192413330078, 0.28342404961586 }, 0.5090365550651166 },
	{ ( float[3] ) { -0.35340607166290283, -0.35108059644699097, -0.7569692730903625 }, 0.3884291977839999 },
	{ ( float[3] ) { 0.9702942371368408, 1.9559880495071411, 0.5030092000961304 }, 0.6783958594596393 },
	{ ( float[3] ) { -0.44922366738319397, -0.5340708494186401, 0.49332818388938904 }, 0.273499860675841 },
	{ ( float[3] ) { 0.21910038590431213, -0.18869644403457642, -0.9284769296646118 }, 0.353513639774125 },
	{ ( float[3] ) { -0.6249111294746399, -0.5278087854385376, 0.15104472637176514 }, 0.25612991488105336 },
	{ ( float[3] ) { 0.6414669752120972, 1.2490779161453247, 1.512622356414795 }, 0.5314718634507278 },
	{ ( float[3] ) { 1.5015686750411987, -0.12497925013303757, -0.5767713785171509 }, 0.5136835858871751 },
	{ ( float[3] ) { 1.4573475122451782, 1.601377248764038, 0.9183969497680664 }, 0.5783959860382992 },
	{ ( float[3] ) { 3.3904337882995605, 1.835252046585083, 0.15620501339435577 }, 0.9890987246074076 },
	{ ( float[3] ) { 0.9742588996887207, 1.1552244424819946, 0.3440767824649811 }, 0.8015655619270939 },
	{ ( float[3] ) { 1.2550206184387207, 1.7410632371902466, 2.266225814819336 }, 0.8720151636753695 },
	{ ( float[3] ) { -0.32464277744293213, -0.4740128219127655, 0.07558748126029968 }, 0.36624025454842596 },
	{ ( float[3] ) { -0.42388296127319336, -0.5424461960792542, 2.2176730632781982 }, 0.6377254472087271 },
	{ ( float[3] ) { 0.4060177505016327, 1.2750823497772217, 0.2779262661933899 }, 0.5258609256022042 },
	{ ( float[3] ) { 0.8770675659179688, -0.13358409702777863, -0.5004835724830627 }, 0.5181131195232239 },
	{ ( float[3] ) { 2.5897791385650635, 1.8556166887283325, 0.7520276308059692 }, 0.6716486599811197 },
	{ ( float[3] ) { 2.18904709815979, 2.1761715412139893, 0.28441157937049866 }, 0.8265888334883378 },
	{ ( float[3] ) { -0.15970905125141144, -0.5866957902908325, 0.9202231764793396 }, 0.4575482781881466 },
	{ ( float[3] ) { 0.8292264342308044, 1.2768759727478027, 0.7535711526870728 }, 0.553576217661705 },
	{ ( float[3] ) { 1.9408544301986694, 2.0827090740203857, 0.889033854007721 }, 0.5795577921137396 },
	{ ( float[3] ) { 0.3998086750507355, -0.29354631900787354, -0.5736058950424194 }, 0.5899679783855138 },
	{ ( float[3] ) { 0.9479551315307617, 0.4127134680747986, 0.12759554386138916 }, 0.6336857425965454 },
	{ ( float[3] ) { -0.02465893141925335, -0.4351319670677185, -0.628934919834137 }, 0.39090755726678117 },
	{ ( float[3] ) { 1.1439034938812256, 1.9081287384033203, 1.4669318199157715 }, 0.666928631209441 },
	{ ( float[3] ) { -0.5721389055252075, -0.5737670660018921, 1.9044047594070435 }, 0.4580029231616362 },
	{ ( float[3] ) { 0.2574453055858612, 1.684492826461792, 1.4951320886611938 }, 0.6195333009842204 },
	{ ( float[3] ) { -0.4477856159210205, -0.3188742399215698, 2.8234903812408447 }, 0.5207689169790386 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
